BEGIN;
TRUNCATE public.ig_dialogues RESTART IDENTITY;

INSERT INTO public.ig_dialogues (title_en, title_ja, location_ja, lines) VALUES
('Long time no see!', 'ひさしぶり！', 'カフェにて ', '[ {"speaker":"mimi","en":"Long time no see!","ja":"ひさしぶり！","pose":"૮₍˶ •. • ⑅₎ა"}, {"speaker":"ten","en":"We met yesterday.","ja":"昨日会ったよね。","pose":"(„• ֊ •„)"}, {"speaker":"mimi","en":"It feels like years!","ja":"何年も会ってない気がする！","pose":"૮₍˶ ˘ ³˘ ⑅₎ა"}, {"speaker":"ten","en":"You''re so dramatic.","ja":"大げさだなあ。","pose":"(„ᵔ ֊ ᵔ„)"}, {"speaker":"mimi","en":"I missed you, though.","ja":"でも会いたかったよ。","pose":"૮₍˶ ᵔ ᵕ ᵔ ⑅₎ა"} ]'::jsonb),
('I''m full.', 'お腹いっぱい。', 'レストランにて ', '[ {"speaker":"ten","en":"How was the pasta?","ja":"パスタどうだった？","pose":"(„• ֊ •„)"}, {"speaker":"mimi","en":"Amazing. I''m so full.","ja":"最高。お腹いっぱい。","pose":"૮₍˶ ᵔ ᵕ ᵔ ⑅₎ა"}, {"speaker":"ten","en":"Great, let''s get the check.","ja":"じゃあお会計しようか。","pose":"(„ᵔ ֊ ᵔ„)"}, {"speaker":"mimi","en":"Wait — one more cake.","ja":"待って、ケーキもうひとつ。","pose":"૮₍˶ ˘ ³˘ ⑅₎ა"}, {"speaker":"ten","en":"...There''s no saving you.","ja":"…もう手に負えない。","pose":"(„• ֊ •„)"} ]'::jsonb),
('I''m on my way!', '今向かってる！', '電話にて ', '[ {"speaker":"ten","en":"Where are you? It''s starting.","ja":"今どこ？始まるよ。","pose":"(„• ֊ •„)"}, {"speaker":"mimi","en":"Relax, I''m on my way!","ja":"大丈夫、今向かってる！","pose":"૮₍˶ ᵔ ᵕ ᵔ ⑅₎ა"}, {"speaker":"ten","en":"Great, see you soon!","ja":"よかった、もうすぐだね！","pose":"(„ᵔ ֊ ᵔ„)"}, {"speaker":"ten","en":"...Is that your pillow?","ja":"…それ枕じゃない？","pose":"(„• ֊ •„)"}, {"speaker":"mimi","en":"My way starts after a nap.","ja":"昼寝のあとに出発するの。","pose":"૮₍˶ -. - ⑅₎ა"} ]'::jsonb),
('Let''s split the bill.', '割り勘にしよう。', 'レジの前で ', '[ {"speaker":"mimi","en":"Let''s split the bill!","ja":"割り勘にしよう！","pose":"૮₍˶ ᵔ ᵕ ᵔ ⑅₎ა"}, {"speaker":"ten","en":"Sure, sounds fair.","ja":"いいよ、公平だね。","pose":"(„ᵔ ֊ ᵔ„)"}, {"speaker":"mimi","en":"You had water, right?","ja":"あなたお水だけだよね？","pose":"૮₍˶ •. • ⑅₎ა"}, {"speaker":"ten","en":"...And you had nine plates.","ja":"…で、9皿食べたよね。","pose":"(„• ֊ •„)"}, {"speaker":"mimi","en":"Friendship has no calories.","ja":"友情にカロリーはないの。","pose":"૮₍˶ ˘ ³˘ ⑅₎ა"} ]'::jsonb),
('I slept like a log.', 'ぐっすり眠った。', '朝の公園で ', '[ {"speaker":"ten","en":"You look great today!","ja":"今日元気そうだね！","pose":"(„ᵔ ֊ ᵔ„)"}, {"speaker":"mimi","en":"I slept like a log!","ja":"丸太みたいに寝たよ！","pose":"૮₍˶ ᵔ ᵕ ᵔ ⑅₎ა"}, {"speaker":"ten","en":"Nice! How many hours?","ja":"いいね！何時間？","pose":"(„• ֊ •„)"}, {"speaker":"mimi","en":"Fourteen. I became a forest.","ja":"14時間。森になってた。","pose":"૮₍˶ -. - ⑅₎ა"}, {"speaker":"ten","en":"That''s hibernation, not sleep.","ja":"それ睡眠じゃなくて冬眠。","pose":"(„ᵔ ֊ ᵔ„)"} ]'::jsonb),
('Can I get a refill?', 'おかわりください。', 'ファミレスにて ', '[ {"speaker":"mimi","en":"Can I get a refill?","ja":"おかわりもらえますか？","pose":"૮₍˶ •. • ⑅₎ა"}, {"speaker":"ten","en":"Of course! More coffee?","ja":"もちろん！コーヒー？","pose":"(„ᵔ ֊ ᵔ„)"}, {"speaker":"mimi","en":"No, miso soup, please.","ja":"ううん、お味噌汁で。","pose":"૮₍˶ •. • ⑅₎ა"}, {"speaker":"ten","en":"...That''s your eighth bowl.","ja":"…もう8杯目だよ。","pose":"(„• ֊ •„)"}, {"speaker":"mimi","en":"Breakfast is a marathon.","ja":"朝食はマラソンなの。","pose":"૮₍˶ ˘ ³˘ ⑅₎ა"} ]'::jsonb),
('I''m just looking, thanks.', '見てるだけです。', 'パン屋にて ', '[ {"speaker":"ten","en":"Welcome! Can I help you?","ja":"いらっしゃいませ！お手伝いします？","pose":"(„ᵔ ֊ ᵔ„)"}, {"speaker":"mimi","en":"I''m just looking, thanks.","ja":"見てるだけです、どうも。","pose":"૮₍˶ •. • ⑅₎ა"}, {"speaker":"ten","en":"...You''re holding five boxes.","ja":"…箱を5つ持ってますよ。","pose":"(„• ֊ •„)"}, {"speaker":"mimi","en":"I look with my hands.","ja":"手で見るタイプなんです。","pose":"૮₍˶ ˘ ³˘ ⑅₎ა"}, {"speaker":"ten","en":"That''s literally shopping.","ja":"それ普通に買い物です。","pose":"(„ᵔ ֊ ᵔ„)"} ]'::jsonb),
('I can''t wait!', '楽しみ！', '前の日の夜 ', '[ {"speaker":"ten","en":"Picnic tomorrow at ten!","ja":"明日10時にピクニック！","pose":"(„ᵔ ֊ ᵔ„)"}, {"speaker":"mimi","en":"I can''t wait!","ja":"楽しみすぎる！","pose":"૮₍˶ ᵔ ᵕ ᵔ ⑅₎ა"}, {"speaker":"ten","en":"Did you pack the sandwiches?","ja":"サンドイッチ作った？","pose":"(„• ֊ •„)"}, {"speaker":"mimi","en":"I couldn''t wait. I ate them.","ja":"待てなくて、食べちゃった。","pose":"૮₍˶ ˘ ³˘ ⑅₎ა"}, {"speaker":"ten","en":"It''s for TOMORROW!","ja":"明日の分だよ！？","pose":"(„⊙ ֊ ⊙„)!!"} ]'::jsonb),
('Could you say that again?', 'もう一度言ってもらえますか？', '道ばたで ', '[ {"speaker":"ten","en":"The station is that way.","ja":"駅はあっちだよ。","pose":"(„• ֊ •„)"}, {"speaker":"mimi","en":"Could you say that again?","ja":"もう一度いいですか？","pose":"૮₍˶ •. • ⑅₎ა"}, {"speaker":"ten","en":"It''s right over there.","ja":"すぐそこだってば。","pose":"(„• ֊ •„)"}, {"speaker":"mimi","en":"One more — your voice is nice.","ja":"もう一回。声が好きで。","pose":"૮₍˶ ᵔ ᵕ ᵔ ⑅₎ა"}, {"speaker":"ten","en":"This isn''t a listening test.","ja":"リスニングテストじゃないよ。","pose":"(„ᵔ ֊ ᵔ„)"} ]'::jsonb),
('What do you do?', 'お仕事は何ですか？', '初対面の会話 ', '[ {"speaker":"ten","en":"So, what do you do?","ja":"お仕事は何ですか？","pose":"(„• ֊ •„)"}, {"speaker":"mimi","en":"I''m a professional.","ja":"プロなんです。","pose":"૮₍˶ ˘ ³˘ ⑅₎ა"}, {"speaker":"ten","en":"A professional... what?","ja":"何の…プロ？","pose":"(„• ֊ •„)"}, {"speaker":"mimi","en":"Napper. Three a day.","ja":"お昼寝の。1日3回。","pose":"૮₍˶ -. - ⑅₎ა"}, {"speaker":"ten","en":"That''s a lifestyle, not a job.","ja":"それ職業じゃなくて生き方。","pose":"(„ᵔ ֊ ᵔ„)"} ]'::jsonb),
('It''s on me.', 'ここは私のおごり。', 'カフェのレジで ', '[ {"speaker":"mimi","en":"Lunch is on me today!","ja":"今日のランチは私のおごり！","pose":"૮₍˶ ᵔ ᵕ ᵔ ⑅₎ა"}, {"speaker":"ten","en":"Wow, thank you!","ja":"わあ、ありがとう！","pose":"(„ᵔ ֊ ᵔ„)"}, {"speaker":"mimi","en":"I''ve got a coupon!","ja":"クーポンあるから！","pose":"૮₍˶ •. • ⑅₎ა"}, {"speaker":"mimi","en":"...It expired in 2019.","ja":"…2019年に切れてた。","pose":"૮₍˶ ⊙ o ⊙ ⑅₎ა"}, {"speaker":"ten","en":"So it''s on me.","ja":"結局、僕のおごりか。","pose":"(„ᵔ ֊ ᵔ„)"} ]'::jsonb),
('Take it easy.', '無理しないでね。', '仕事終わりに ', '[ {"speaker":"ten","en":"Take it easy, you earned it!","ja":"お疲れさま。無理しないでね！","pose":"(„ᵔ ֊ ᵔ„)"}, {"speaker":"mimi","en":"Okay! Taking it easy!","ja":"はーい、無理しなーい！","pose":"૮₍˶ ᵔ ᵕ ᵔ ⑅₎ა"}, {"speaker":"ten","en":"...Why are you lying down?","ja":"…なんで寝転んでるの？","pose":"(„• ֊ •„)"}, {"speaker":"mimi","en":"You said take it easy.","ja":"無理しないでって言ったでしょ。","pose":"૮₍˶ -. - ⑅₎ა"}, {"speaker":"ten","en":"Not on the SIDEWALK!","ja":"歩道はダメ！","pose":"(„⊙ ֊ ⊙„)!!"} ]'::jsonb),
('How have you been?', '元気にしてた？', '久しぶりの再会 ', '[ {"speaker":"ten","en":"How have you been?","ja":"元気にしてた？","pose":"(„• ֊ •„)"}, {"speaker":"mimi","en":"Pretty good! You?","ja":"まあまあ元気！そっちは？","pose":"૮₍˶ ᵔ ᵕ ᵔ ⑅₎ა"}, {"speaker":"ten","en":"Good! Been keeping busy?","ja":"いいね！忙しくしてた？","pose":"(„ᵔ ֊ ᵔ„)"}, {"speaker":"ten","en":"...Are you napping right now?","ja":"…今、昼寝してない？","pose":"(„• ֊ •„)"}, {"speaker":"mimi","en":"I''ve been resting. Professionally.","ja":"プロ級に休んでたの。","pose":"૮₍˶ -. - ⑅₎ა"} ]'::jsonb),
('Any plans for the rest of the day?', '今日この後の予定は？', 'お昼休みに ', '[ {"speaker":"ten","en":"Any plans for the rest of the day?","ja":"今日この後の予定は？","pose":"(„• ֊ •„)"}, {"speaker":"mimi","en":"Big plans!","ja":"予定たっぷり！","pose":"૮₍˶ ᵔ ᵕ ᵔ ⑅₎ა"}, {"speaker":"ten","en":"Nice — like what?","ja":"いいね、何するの？","pose":"(„ᵔ ֊ ᵔ„)"}, {"speaker":"mimi","en":"Lunch, then planning dinner.","ja":"お昼食べて、晩ごはんの計画。","pose":"૮₍˶ ˘ ³˘ ⑅₎ა"}, {"speaker":"ten","en":"...So, just meals.","ja":"…つまり、ごはんだけ。","pose":"(„• ֊ •„)"} ]'::jsonb);

COMMIT;
