CREATE TABLE IF NOT EXISTS public.ig_words (
  id serial PRIMARY KEY,
  word text NOT NULL,
  word_ja text NOT NULL,
  example_en text NOT NULL,
  example_ja text NOT NULL
);
ALTER TABLE public.ig_words ENABLE ROW LEVEL SECURITY;
-- service-role-only table (read by edge function); no policies needed.

INSERT INTO public.ig_words (word, word_ja, example_en, example_ja) VALUES
('actually', '実は／実際に', 'Actually, I love natto.', '実は、納豆が大好きなんです。'),
('anyway', 'とにかく／まあ', 'Anyway, let''s just go.', 'とにかく、もう行きましょうよ。'),
('by the way', 'ところで', 'By the way, are you hungry?', 'ところで、お腹すいてる？'),
('kind of', 'ちょっと／なんか', 'I''m kind of tired today.', '今日、なんかちょっと疲れてて。'),
('a little', '少し／ちょっと', 'Can you speak a little slower?', 'もう少しゆっくり話してもらえますか？'),
('nervous', '緊張している', 'I''m so nervous about the test.', 'テストのことがすごく緊張してる。'),
('excited', 'ワクワクしている', 'I''m really excited about the trip.', 'その旅行がすごく楽しみで。'),
('exhausted', 'ぐったり疲れた', 'I''m completely exhausted right now.', '今、もうぐったりです。'),
('grab', 'さっと取る／食べる', 'Let''s grab some coffee later.', '後でコーヒー飲みに行こうよ。'),
('hang out', '(一緒に)遊ぶ／つるむ', 'Do you want to hang out Saturday?', '土曜日一緒に遊ばない？'),
('catch up', '近況を話す', 'We should catch up sometime.', 'また近況話しましょうよ。'),
('treat', 'おごる', 'Let me treat you this time.', '今回は私がおごるよ。'),
('split', '割り勘にする', 'Should we split the bill?', '割り勘にしますか？'),
('almost', 'もう少しで／ほぼ', 'I almost missed the train.', 'もう少しで電車に乗り遅れるところだった。'),
('barely', 'やっと／かろうじて', 'I barely made it on time.', 'ギリギリ間に合いました。'),
('honestly', '正直に言うと', 'Honestly, it wasn''t that good.', '正直に言うと、あんまりよくなかったです。'),
('apparently', '〜らしい', 'Apparently the café is closed today.', 'そのカフェ、今日は休みらしいですよ。'),
('eventually', 'いつかは／最終的に', 'I''ll study English eventually.', 'いつかは英語の勉強しますよ。'),
('recently', '最近', 'Have you eaten out recently?', '最近外食しましたか？'),
('lately', '近頃', 'I haven''t slept well lately.', '近頃、あんまりよく眠れていなくて。'),
('somehow', 'なんとか／どうにか', 'I somehow finished on time.', 'なんとか時間内に終わりました。'),
('totally', 'まったく／完全に', 'I totally forgot about it.', 'すっかり忘れてた。'),
('seriously', '本当に／マジで', 'Seriously? That''s so funny!', 'マジで？それめちゃくちゃ面白い！'),
('probably', 'たぶん', 'She''s probably still at work.', '彼女はたぶんまだ仕事中だよ。'),
('suppose', '〜だと思う', 'I suppose we should leave now.', 'そろそろ行った方がいいと思いますよ。'),
('wonder', 'かな〜と思う／不思議に思う', 'I wonder if he''s okay.', '彼、大丈夫かなって思って。'),
('figure out', '理解する／解決する', 'I can''t figure out this menu.', 'このメニュー、読み方が全然わからない。'),
('end up', '結局〜になる', 'We ended up eating ramen.', '結局ラーメンを食べることになりました。'),
('turn out', '〜だとわかる', 'It turned out to be delicious.', '食べてみたらすごくおいしかった。'),
('bring up', '話題を出す', 'Don''t bring that up now.', 'そのことは今持ち出さないでよ。'),
('get used to', '慣れる', 'I''m getting used to spicy food.', '辛い食べ物に慣れてきました。'),
('look forward to', '楽しみにする', 'I look forward to seeing you.', 'お会いするのを楽しみにしています。'),
('give up', '諦める', 'Don''t give up so fast.', 'そんなに早く諦めないで。'),
('run out', '〜がなくなる', 'I ran out of cash.', 'お金が底をついてしまって。'),
('mess up', '失敗する', 'I really messed up today.', '今日は本当にしくじってしまいました。'),
('cheer up', '元気を出す', 'Come on, cheer up!', 'ほら、元気出して！'),
('show up', '現れる', 'He didn''t show up again.', 'また彼は来なかったよ。'),
('pick up', '拾う／迎えに行く', 'Can you pick me up at seven?', '7時に迎えに来てもらえる？'),
('move on', '先へ進む／気持ちを切り替える', 'It''s time to move on.', 'そろそろ気持ちを切り替える時だよ。'),
('put off', '先延ばしにする', 'I keep putting it off.', 'ずっと先延ばしにしちゃってる。'),
('skip', '飛ばす／サボる', 'Can I skip this one?', 'これ、飛ばしてもいいですか？'),
('regret', '後悔する', 'I regret eating so much.', '食べすぎたって後悔してる。'),
('remind', '思い出させる', 'Please remind me tomorrow.', '明日、思い出させてくれますか？'),
('prefer', '〜の方が好き', 'I prefer tea over coffee.', 'コーヒーよりお茶の方が好きです。'),
('afford', '〜する余裕がある', 'I can''t afford that right now.', '今はそれを買う余裕がないんです。'),
('worth', '〜の価値がある', 'The movie was worth watching.', 'その映画、見る価値ありましたよ。'),
('awkward', '気まずい', 'That conversation was so awkward.', 'あの会話、めちゃくちゃ気まずかった。'),
('embarrassed', '恥ずかしい', 'I was so embarrassed at work.', '職場ですごく恥ずかしかったんです。'),
('relieved', 'ほっとした', 'I''m so relieved it''s over.', '終わってほっとしました。'),
('annoyed', 'イラっとした', 'I got a little annoyed honestly.', '正直ちょっとイラっとしました。'),
('overwhelmed', '圧倒された／いっぱいいっぱい', 'I feel overwhelmed these days.', '最近いっぱいいっぱいな感じがして。'),
('jealous', '羨ましい／嫉妬した', 'I''m a little jealous of her.', '彼女のこと、ちょっと羨ましいな。'),
('guilty', '罪悪感がある', 'I feel guilty for being late.', '遅刻したこと、罪悪感があります。'),
('confident', '自信がある', 'Try to sound more confident.', 'もっと自信を持って話してみて。'),
('curious', '気になる／好奇心がある', 'I''m curious about your hometown.', '出身地のこと、気になります。'),
('bored', '退屈な', 'I''m so bored right now.', '今すごく退屈なんです。'),
('upset', '気分が悪い／動揺している', 'She seemed a little upset.', '彼女、少し動揺してるみたいでした。'),
('mood', '気分', 'I''m not in the mood today.', '今日はちょっとその気分じゃないな。'),
('attitude', '態度', 'His attitude surprised me.', '彼の態度にびっくりしました。'),
('typical', 'いかにも〜らしい', 'That''s so typical of him.', 'いかにも彼らしいよね。'),
('random', '突然の／適当な', 'That was a random question.', '急にその質問、何ですか。'),
('deal', 'こと／問題', 'It''s not a big deal.', 'たいしたことじゃないよ。'),
('hang on', 'ちょっと待って', 'Hang on, let me think.', 'ちょっと待って、考えさせて。'),
('fair enough', 'まあそうだね', 'Fair enough, I see your point.', 'まあそうだね、言いたいことはわかる。'),
('for real', '本当に', 'For real? I had no idea.', '本当に？全然知らなかった。'),
('no wonder', 'どうりで', 'No wonder you''re so tired.', 'どうりで疲れてるわけだ。'),
('right away', 'すぐに', 'I''ll be there right away.', 'すぐ行きます。'),
('for good', '永遠に／ずっと', 'She moved to Osaka for good.', '彼女は大阪に永久に引っ越しました。'),
('at least', '少なくとも', 'At least we tried.', '少なくとも、やってみたじゃないですか。'),
('as usual', 'いつも通り', 'He was late as usual.', '彼はいつも通り遅刻してました。'),
('on purpose', 'わざと', 'I didn''t do it on purpose.', 'わざとやったわけじゃないです。'),
('in a row', '連続して', 'I worked five days in a row.', '5日連続で仕事しました。'),
('in charge', '担当して', 'Who is in charge today?', '今日は誰が担当ですか？'),
('on time', '時間通りに', 'Let''s try to be on time.', '時間通りに行きましょう。'),
('run into', '偶然会う', 'I ran into my teacher today.', '今日、先生に偶然会ったんです。'),
('mix up', '混同する', 'I always mix up those two words.', 'その二つの言葉、いつもごっちゃになります。'),
('come across', '偶然見つける', 'I came across a great café.', '素敵なカフェを偶然見つけました。'),
('point out', '指摘する', 'Can you point out my mistakes?', '間違いを指摘してもらえますか？'),
('get along', '仲良くやる', 'Do you get along with your boss?', '上司とは仲良くやってますか？'),
('settle down', '落ち着く', 'Things will settle down soon.', 'そのうち落ち着くよ。'),
('give it a shot', '試してみる', 'Just give it a shot.', 'とりあえずやってみなよ。'),
('make sense', '理解できる／筋が通る', 'Does this make sense to you?', 'これ、理解できますか？'),
('keep in touch', '連絡を取り合う', 'Let''s keep in touch, okay?', '連絡取り合いましょうね。'),
('bring it up', '話題を切り出す', 'She finally brought it up.', '彼女がやっとそのことを切り出した。'),
('go through', '経験する／調べる', 'She went through a tough time.', '彼女は大変な時期を経験しました。'),
('back out', '約束を破る／引く', 'He backed out at the last minute.', '彼は土壇場で約束を破りました。'),
('wear off', '効き目が切れる', 'The excitement wore off quickly.', 'テンションはすぐに冷めました。'),
('fit in', '馴染む', 'It''s hard to fit in here.', 'ここに馴染むのって難しい。'),
('come up with', '思いつく', 'I can''t come up with an idea.', 'アイデアが全然思い浮かばない。'),
('get over', '立ち直る', 'I''m not over it yet.', 'まだ立ち直れていないんです。'),
('pull off', 'やり遂げる', 'I can''t believe we pulled it off.', 'やり遂げられたなんて信じられない。'),
('stress out', 'ストレスを感じる', 'That kind of thing stresses me out.', 'そういうことってすごくストレスになります。'),
('tight', '忙しい／余裕がない', 'My schedule is really tight.', 'スケジュールがかなりタイトなんです。'),
('quick', 'さっと／手短な', 'Can I ask a quick question?', '一つ、さっと聞いてもいいですか？'),
('smooth', 'スムーズな', 'Everything went really smooth.', 'すべてがスムーズに進みました。'),
('rough', '大変な', 'It''s been a rough week.', '今週はなかなかキツかったです。'),
('casual', 'カジュアルな／気軽な', 'Let''s keep it casual today.', '今日は気軽な感じでいきましょう。'),
('proper', 'ちゃんとした', 'I need a proper meal today.', '今日はちゃんとしたご飯が食べたい。'),
('catch on', '理解する／流行る', 'I didn''t catch on at first.', '最初は全然理解できなかったです。'),
('sort out', '解決する／整理する', 'I need to sort this out.', 'これを何とか解決しないと。');

-- 100 words = 100 Mondays of content.
